# Generated by Django 4.2.16 on 2024-12-07 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
                ('castumername', models.CharField(max_length=50)),
                ('total_sum', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('is_paid', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
                ('name_dish', models.CharField(max_length=50)),
                ('descriptions', models.TextField()),
                ('time_category', models.CharField(choices=[('BREAKFEST', 'Завтрак'), ('LUNCH', 'Обед'), ('DINNER', 'Ужин'), ('dessert', 'Десерт'), ('Drinks', 'Напитки'), ('Snacks', 'Салаты')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prf_time', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='media/images')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('vip', 'vip'), ('table', 'Стол'), ('Cud', 'Кад')], max_length=50)),
                ('max_person', models.IntegerField()),
                ('status', models.CharField(choices=[('Full', 'FULL'), ('Free', 'Free')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='apis.bill')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.dish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.table'),
        ),
    ]
